/**
 * Graph Tab View TypeScript Interfaces
 * Defines types for the Memory Graph visualization in the Ideation Agent
 */

// ============================================================================
// Block Types
// ============================================================================

// Canonical block types (21 primary types)
export type CanonicalBlockType =
  // Core types (11)
  | "insight"
  | "fact"
  | "assumption"
  | "question"
  | "decision"
  | "action"
  | "requirement"
  | "option"
  | "pattern"
  | "synthesis"
  | "meta"
  // New types (10)
  | "constraint"
  | "blocker"
  | "epic"
  | "story"
  | "task"
  | "bug"
  | "persona"
  | "milestone"
  | "evaluation"
  | "learning";

// All block types (canonical + legacy for backward compat)
export type BlockType =
  | CanonicalBlockType
  | "content"
  | "link"
  | "derived"
  | "cycle"
  | "placeholder"
  | "stakeholder_view"
  | "topic"
  | "external";

export type GraphType =
  // Core dimensions (10)
  | "problem"
  | "solution"
  | "market"
  | "risk"
  | "fit"
  | "business"
  | "spec"
  | "distribution"
  | "marketing"
  | "manufacturing"
  // New dimensions (7)
  | "user"
  | "competition"
  | "validation"
  | "tasks"
  | "timeline"
  | "customer"
  | "product";

export type BlockStatus =
  | "draft"
  | "active"
  | "validated"
  | "superseded"
  | "abandoned";

export type AbstractionLevel =
  | "vision"
  | "strategy"
  | "tactic"
  | "implementation";

// Internal data source types - where the block data originated from
// Includes both frontend display types and server-side source types
export type SourceType =
  // Frontend display types
  | "chat" // Extracted from chat conversation
  | "artifact" // From markdown artifacts
  | "memory_file" // From ideation agent memory files
  | "memory_db" // From memory database (blocks/links)
  | "user_created" // Manually created by user
  | "ai_generated" // Generated by AI during analysis
  // Server-side source types (from source-collector.ts)
  | "conversation" // Raw conversation messages
  | "conversation_insight" // AI-synthesized insights from conversation
  | "user_block" // User-created blocks
  | "external"; // External/imported content

// External attribution types - for research/evidence attribution
export type AttributionType =
  | "research_firm"
  | "primary_research"
  | "expert"
  | "anecdote"
  | "assumption"
  | "unknown";

// ============================================================================
// Source Location Types (for navigation)
// ============================================================================

export type SourceLocationType = "chat" | "artifact" | "memory_db" | "external";

export interface SourceLocation {
  type: SourceLocationType;
  // For chat navigation
  messageId?: string;
  turnIndex?: number;
  // For artifact navigation
  artifactId?: string;
  artifactTitle?: string; // Human-readable title for display
  artifactSection?: string;
  // For memory database navigation
  tableName?: "blocks" | "links" | "graphs" | "sessions" | "files";
  blockId?: string;
  // For memory file navigation (when tableName is "files")
  memoryFileType?: string; // e.g., "core_beliefs", "synthesis", etc.
  // For memory file navigation
  memoryFileTitle?: string; // Human-readable title for display
  // For external URLs
  url?: string;
}

// Source info for lineage tracking - stored in block properties
export interface SourceInfo {
  id: string;
  type: string;
  title?: string | null;
  weight?: number | null;
}

// ============================================================================
// Link Types
// ============================================================================

export type LinkType =
  | "addresses"
  | "creates"
  | "requires"
  | "blocks"
  | "unblocks"
  | "supersedes"
  | "refines"
  | "replaces"
  | "contradicts"
  | "evidence_for"
  | "derived_from"
  | "implements"
  | "implemented_by"
  | "alternative_to"
  | "synthesizes"
  | "instance_of"
  | "about"
  | "excludes"
  | "includes"
  | "constrained_by"
  | "validates_claim";

export type LinkDegree = "full" | "partial" | "minimal";

// ============================================================================
// File Reference Types (from T9.6)
// ============================================================================

export interface FileReference {
  filePath: string;
  fileName: string;
  section?: string;
  lineRange?: { start: number; end: number };
  referenceType: "spec" | "code" | "doc" | "other";
}

// ============================================================================
// Graph Node Interface
// ============================================================================

export interface GraphNode {
  id: string;

  // Display properties
  label: string;
  subLabel?: string;
  title?: string | null; // Short 3-5 word summary for quick identification

  // Block metadata
  blockType: BlockType; // Primary type (first in blockTypes, for backward compat)
  blockTypes?: BlockType[]; // All block types (new multi-type support)
  graphMembership: GraphType[];
  status: BlockStatus;
  confidence: number;
  abstractionLevel?: AbstractionLevel;

  // Temporal (from Scenario 8)
  createdAt: string;
  updatedAt: string;
  when?: string;
  duration?: string;
  plannedFor?: string;
  validUntil?: string;

  // Full content (for inspector)
  content: string;
  properties: Record<string, unknown>;

  // Internal data source - where this block originated from
  sourceType?: SourceType;
  sourceLocation?: SourceLocation;
  // All sources that contributed to this insight (for multi-source lineage)
  allSources?: SourceInfo[];

  // External attribution - research/evidence source (from Scenario 12)
  attributionType?: AttributionType;
  attributionName?: string;
  attributionDate?: string;
  verifiable?: boolean;

  // Objectivity & certainty (from Scenarios 4, 13)
  objectivity?: "objective" | "subjective" | "mixed";
  hypothetical?: boolean;
  condition?: string;

  // Evidence chain (from Scenario 20)
  evidenceStrength?: "strong" | "moderate" | "weak";
  derivedConfidence?: number;

  // Derived block properties (from Scenario 19)
  formula?: string;
  computedValue?: unknown;
  computedAt?: string;
  stale?: boolean;
  overrideValue?: unknown;
  overrideReason?: string;

  // Action block properties (from Scenario 26)
  actionType?: "validate" | "research" | "build" | "decide" | "other";
  requiredCount?: number;
  completedCount?: number;
  assignedTo?: string;
  dueDate?: string;
  outcome?: "validated" | "invalidated" | "inconclusive";

  // Assumption block properties (from Scenario 21)
  impliedBy?: string;
  surfacedBy?: "ai" | "user" | "advisor";
  assumptionStatus?: "unvalidated" | "validated" | "invalidated" | "dismissed";
  criticality?: "critical" | "important" | "minor";

  // Decision/Option block properties (from Scenario 16)
  topic?: string;
  decidedOption?: string;
  decisionRationale?: string;
  selectionStatus?: "exploring" | "selected" | "rejected";
  alternativeTo?: string[];

  // Stakeholder view properties (from Scenario 24)
  stakeholder?: string;
  stakeholderRole?:
    | "decision_maker"
    | "domain_expert"
    | "advisor"
    | "team_member";
  viewStatus?: "active" | "adopted" | "overruled" | "withdrawn";

  // Placeholder block properties (from Scenario 23)
  placeholderFor?: string;
  researchQuery?: string;
  existenceConfirmed?: boolean;
  detailsUnknown?: boolean;

  // External block properties (from Scenario 25)
  url?: string;
  snapshotDate?: string;
  urlStatus?: "alive" | "redirected" | "dead" | "changed";
  domainCredibility?: "high" | "medium" | "low" | "very_low";

  // Meta block properties (from Scenario 5)
  metaType?:
    | "uncertainty"
    | "research_needed"
    | "assessment"
    | "question"
    | "commitment";
  about?: string;
  resolved?: boolean;

  // Cycle detection (from Scenario 22)
  cycleId?: string;
  cyclePosition?: number;
  cycleType?: "blocking" | "reinforcing";

  // Cross-idea patterns (from Scenario 15)
  scope?: string;
  instanceOf?: string;
  sharedWith?: string[];
  portfolioTag?: string;

  // Context-qualified properties (from Scenario 18)
  variesBy?: string;

  // Synthesis block properties (from Scenario 14)
  synthesizes?: string[];
  clusterTheme?: string;

  // Option block properties (from Scenario 16)
  decision?: string;

  // Topic block properties (from T7.3)
  decidedView?: string;
  decisionDate?: string;
  topicRationale?: string;
  stakeholderViews?: string[];

  // Assumption validation tracking (from Scenario 21)
  validationMethod?: string;
  validatedBy?: string;
  validatedAt?: string;

  // Evidence chain status (from Scenario 20)
  evidenceStatus?: "active" | "source_invalidated" | "source_superseded";

  // Placeholder partial info (from Scenario 23)
  partialInfo?: string[];

  // Stakeholder view resolution (from Scenario 24)
  incorporatedInto?: string;
  overruledReason?: string;

  // Cycle resolution (from Scenario 22)
  breakStrategy?: string;
  breakPoint?: string;

  // Artifact link (from T8.3)
  artifactId?: string;
  artifactType?: string;
  artifactSection?: string;

  // File references (from T9.6)
  fileReferences?: FileReference[];

  // Visual hints
  isHighlighted?: boolean;
  isSelected?: boolean;
  cluster?: string;
}

// ============================================================================
// Clustering Types
// ============================================================================

/**
 * Strategy for auto-assigning nodes to clusters
 */
export type ClusterStrategy =
  | "none" // No clustering
  | "graphMembership" // Group by graphMembership[0] (problem, solution, market, etc.)
  | "blockType" // Group by blockType (content, synthesis, decision, etc.)
  | "abstraction" // Group by abstractionLevel (vision, strategy, tactic, implementation)
  | "status" // Group by status (draft, active, validated, etc.)
  | "custom"; // User-defined groups

/**
 * Configuration for graph clustering behavior
 */
export interface ClusterConfig {
  /** The clustering strategy to use */
  strategy: ClusterStrategy;
  /** For custom strategy: maps clusterName -> nodeIds */
  customGroups?: Record<string, string[]>;
  /** Cluster tightness: 0.0 (loose) to 1.0 (tight) */
  strength: number;
}

/**
 * Default cluster configuration
 */
export const defaultClusterConfig: ClusterConfig = {
  strategy: "none",
  strength: 0.7,
};

// ============================================================================
// Graph Edge Interface
// ============================================================================

export interface GraphEdge {
  id: string;
  source: string;
  target: string;

  // Link metadata
  linkType: LinkType;
  degree?: LinkDegree;
  confidence?: number;
  reason?: string;
  status: "active" | "superseded" | "removed";

  // Visual hints
  isHighlighted?: boolean;
}

// ============================================================================
// Visual Mapping Types
// ============================================================================

export const nodeColors: Record<BlockType, string> = {
  // Canonical block types (11)
  insight: "#8B5CF6", // Purple
  fact: "#3B82F6", // Blue
  assumption: "#FBBF24", // Yellow
  question: "#F59E0B", // Amber
  decision: "#EF4444", // Red
  action: "#22C55E", // Green
  requirement: "#06B6D4", // Cyan
  option: "#F97316", // Orange
  pattern: "#EC4899", // Pink
  synthesis: "#A855F7", // Violet
  meta: "#6B7280", // Gray
  // New canonical block types (10)
  constraint: "#FF5722", // Deep Orange
  blocker: "#D32F2F", // Dark Red
  epic: "#7B1FA2", // Dark Purple
  story: "#512DA8", // Deep Purple
  task: "#1976D2", // Dark Blue
  bug: "#C62828", // Red 800
  persona: "#00796B", // Teal
  milestone: "#FFA000", // Amber
  evaluation: "#388E3C", // Green 700
  learning: "#5D4037", // Brown 700
  // Legacy block types
  content: "#3B82F6", // Blue (same as fact)
  link: "#6B7280", // Gray (usually hidden)
  derived: "#14B8A6", // Teal
  cycle: "#DC2626", // Dark red
  placeholder: "#9CA3AF", // Light gray
  stakeholder_view: "#06B6D4", // Cyan
  topic: "#0EA5E9", // Light blue
  external: "#84CC16", // Lime
};

export const graphColors: Record<GraphType, string> = {
  // Core dimensions (10)
  problem: "#EF4444", // Red
  solution: "#22C55E", // Green
  market: "#3B82F6", // Blue
  risk: "#F59E0B", // Amber
  fit: "#8B5CF6", // Purple
  business: "#14B8A6", // Teal
  spec: "#6B7280", // Gray
  distribution: "#D946EF", // Fuchsia
  marketing: "#F43F5E", // Rose
  manufacturing: "#78716C", // Stone
  // New dimensions (7)
  user: "#7C3AED", // Violet
  competition: "#DC2626", // Red 600
  validation: "#059669", // Emerald
  tasks: "#2563EB", // Blue 600
  timeline: "#9333EA", // Purple 600
  customer: "#0891B2", // Cyan 600
  product: "#65A30D", // Lime 600
};

export type NodeShape =
  | "hexagon"
  | "diamond"
  | "circle"
  | "triangle"
  | "square"
  | "pentagon"
  | "star"
  | "octagon"
  | "cross"
  | "pill";

export const nodeShapes: Record<GraphType, NodeShape> = {
  // Core dimensions (10)
  problem: "hexagon",
  solution: "diamond",
  market: "circle",
  risk: "triangle",
  fit: "square",
  business: "pentagon",
  spec: "star",
  distribution: "octagon",
  marketing: "cross",
  manufacturing: "pill",
  // New dimensions (7)
  user: "circle",
  competition: "hexagon",
  validation: "diamond",
  tasks: "square",
  timeline: "octagon",
  customer: "pentagon",
  product: "star",
};

export const edgeColors: Record<LinkType, string> = {
  addresses: "#22C55E", // Green - positive
  creates: "#3B82F6", // Blue - creative
  requires: "#F59E0B", // Amber - dependency
  blocks: "#EF4444", // Red - blocker
  unblocks: "#22C55E", // Green - positive
  supersedes: "#6B7280", // Gray - temporal
  refines: "#8B5CF6", // Purple - refinement
  replaces: "#6B7280", // Gray - temporal
  contradicts: "#EF4444", // Red - conflict
  evidence_for: "#3B82F6", // Blue - support
  derived_from: "#14B8A6", // Teal - derivation
  implements: "#22C55E", // Green - implementation
  implemented_by: "#22C55E", // Green - implementation
  alternative_to: "#F97316", // Orange - options
  synthesizes: "#8B5CF6", // Purple - synthesis
  instance_of: "#EC4899", // Pink - pattern
  about: "#6B7280", // Gray - reference
  excludes: "#EF4444", // Red - exclusion
  includes: "#22C55E", // Green - inclusion
  constrained_by: "#F59E0B", // Amber - constraint
  validates_claim: "#3B82F6", // Blue - validation
};

export type EdgeStyle = "solid" | "dashed" | "dotted";

export const edgeStyles: Record<LinkType, EdgeStyle> = {
  addresses: "solid",
  creates: "solid",
  requires: "dashed",
  blocks: "solid",
  unblocks: "solid",
  supersedes: "dotted",
  refines: "dashed",
  replaces: "dotted",
  contradicts: "solid",
  evidence_for: "solid",
  derived_from: "dashed",
  implements: "solid",
  implemented_by: "solid",
  alternative_to: "dashed",
  synthesizes: "solid",
  instance_of: "dotted",
  about: "dotted",
  excludes: "solid",
  includes: "solid",
  constrained_by: "dashed",
  validates_claim: "solid",
};

// ============================================================================
// API Response Types (for transformation)
// ============================================================================

export interface ApiBlock {
  id: string;
  type: string;
  blockTypes?: string[]; // New multi-type support
  title?: string | null; // Short 3-5 word summary
  content: string;
  properties: Record<string, unknown>;
  status: string;
  // Support both snake_case (type definition) and camelCase (actual API response)
  created_at?: string;
  updated_at?: string;
  createdAt?: string;
  updatedAt?: string;
  // Optional top-level fields from API (newer format)
  confidence?: number;
  abstractionLevel?: string;
  graphMembership?: string[];
}

export interface ApiLink {
  id: string;
  type: "link";
  properties: {
    link_type: string;
    source: string;
    target: string;
    degree?: string;
    confidence?: number;
    reason?: string;
    status?: string;
  };
}

// ============================================================================
// Filter Types
// ============================================================================

export interface GraphFilters {
  graphTypes: GraphType[];
  blockTypes: BlockType[];
  statuses: BlockStatus[];
  abstractionLevels: AbstractionLevel[];
  sourceTypes: SourceType[];
  confidenceRange: [number, number];
}

export const defaultGraphFilters: GraphFilters = {
  graphTypes: [],
  blockTypes: [],
  statuses: [],
  abstractionLevels: [],
  sourceTypes: [],
  confidenceRange: [0, 1],
};

// ============================================================================
// Graph Data State
// ============================================================================

export interface GraphData {
  nodes: GraphNode[];
  edges: GraphEdge[];
}

export interface GraphDataState {
  data: GraphData;
  isLoading: boolean;
  error: string | null;
  lastUpdated: string | null;
}

// ============================================================================
// Graph Snapshot Types (for version control)
// ============================================================================

/**
 * Summary of a graph snapshot (metadata without full data)
 */
export interface GraphSnapshotSummary {
  id: string;
  sessionId: string;
  name: string;
  description: string | null;
  blockCount: number;
  linkCount: number;
  createdAt: string;
}

/**
 * State for graph snapshot/versioning feature
 */
export interface GraphSnapshotsState {
  snapshots: GraphSnapshotSummary[];
  isLoading: boolean;
  isSaving: boolean;
  isRestoring: boolean;
  error: string | null;
}
