-- Migration 025: Specification, Build, and Self-Improvement Agent Tables
-- Created: 2026-01-10
-- Purpose: Support for Spec Agent → Build Agent → SIA pipeline

-- ============================================================================
-- SPECIFICATIONS TABLE
-- Tracks specs generated by Specification Agent
-- ============================================================================

CREATE TABLE IF NOT EXISTS specifications (
    id TEXT PRIMARY KEY,
    idea_slug TEXT NOT NULL,
    user_slug TEXT NOT NULL,
    spec_path TEXT NOT NULL,           -- Path to spec.md
    tasks_path TEXT NOT NULL,          -- Path to tasks.md
    task_count INTEGER DEFAULT 0,
    status TEXT DEFAULT 'draft',       -- draft, approved, in_progress, complete, failed
    complexity TEXT DEFAULT 'medium',  -- low, medium, high
    estimated_hours REAL,
    created_at TEXT DEFAULT (datetime('now')),
    approved_at TEXT,
    approved_by TEXT,
    completed_at TEXT,

    -- Context references (from idea folder)
    context_refs TEXT,                 -- JSON: paths to referenced documents
    patterns_ref TEXT,                 -- JSON: CLAUDE.md sections referenced

    -- Validation
    missing_inputs TEXT,               -- JSON: documents that should be completed first
    validation_errors TEXT             -- JSON: any spec validation issues
);

CREATE INDEX IF NOT EXISTS idx_specifications_idea ON specifications(idea_slug, user_slug);
CREATE INDEX IF NOT EXISTS idx_specifications_status ON specifications(status);

-- ============================================================================
-- ATOMIC TASKS TABLE
-- Mirrors tasks.md but queryable, tracks execution
-- ============================================================================

CREATE TABLE IF NOT EXISTS atomic_tasks (
    id TEXT PRIMARY KEY,
    spec_id TEXT NOT NULL,
    task_number INTEGER NOT NULL,      -- Order within spec
    phase TEXT NOT NULL,               -- database, api, ui, tests, etc.
    action TEXT NOT NULL,              -- CREATE, UPDATE, ADD, DELETE, VERIFY
    file_path TEXT NOT NULL,

    -- Task details
    requirements TEXT NOT NULL,        -- JSON array of requirements
    gotchas TEXT,                      -- JSON array of gotchas (from KB)
    validation_command TEXT,           -- Command to validate task
    expected_validation TEXT,          -- Expected validation result
    code_template TEXT,                -- Optional code template
    depends_on TEXT,                   -- JSON array of task IDs

    -- Execution state
    status TEXT DEFAULT 'pending',     -- pending, in_progress, complete, failed, blocked, skipped
    execution_id TEXT,                 -- Which build execution
    assigned_to TEXT,                  -- Loop ID
    started_at TEXT,
    completed_at TEXT,
    actual_diff TEXT,                  -- Git diff of actual changes
    notes TEXT,

    FOREIGN KEY (spec_id) REFERENCES specifications(id)
);

CREATE INDEX IF NOT EXISTS idx_atomic_tasks_spec ON atomic_tasks(spec_id);
CREATE INDEX IF NOT EXISTS idx_atomic_tasks_status ON atomic_tasks(status);
CREATE INDEX IF NOT EXISTS idx_atomic_tasks_file ON atomic_tasks(file_path);

-- ============================================================================
-- BUILD EXECUTIONS TABLE
-- Tracks Build Agent execution runs
-- ============================================================================

CREATE TABLE IF NOT EXISTS build_executions (
    id TEXT PRIMARY KEY,
    spec_id TEXT NOT NULL,
    loop_id TEXT NOT NULL,
    branch_name TEXT NOT NULL,

    -- Execution state
    status TEXT DEFAULT 'pending',     -- pending, priming, running, validating, completed, failed
    current_task_id TEXT,

    -- Progress tracking
    tasks_total INTEGER DEFAULT 0,
    tasks_completed INTEGER DEFAULT 0,
    tasks_failed INTEGER DEFAULT 0,
    tasks_skipped INTEGER DEFAULT 0,

    -- Timing
    started_at TEXT,
    primed_at TEXT,                    -- When context loading finished
    completed_at TEXT,

    -- Results
    execution_log TEXT,                -- JSON array of task results
    final_validation TEXT,             -- JSON: full validation results
    git_commits TEXT,                  -- JSON array of commit SHAs

    -- Options used
    dry_run INTEGER DEFAULT 0,
    skip_validation INTEGER DEFAULT 0,

    FOREIGN KEY (spec_id) REFERENCES specifications(id),
    FOREIGN KEY (loop_id) REFERENCES loops(id)
);

CREATE INDEX IF NOT EXISTS idx_build_executions_spec ON build_executions(spec_id);
CREATE INDEX IF NOT EXISTS idx_build_executions_status ON build_executions(status);
CREATE INDEX IF NOT EXISTS idx_build_executions_loop ON build_executions(loop_id);

-- ============================================================================
-- SYSTEM REVIEWS TABLE
-- SIA analysis of sessions
-- ============================================================================

CREATE TABLE IF NOT EXISTS system_reviews (
    id TEXT PRIMARY KEY,

    -- Session context
    agent_type TEXT NOT NULL,          -- ideation, specification, build
    session_id TEXT,
    idea_slug TEXT,
    loop_id TEXT,

    -- Outcome analysis
    outcome TEXT NOT NULL,             -- success, failure, partial
    outcome_reason TEXT,

    -- Divergence analysis
    plan_summary TEXT,                 -- What was planned
    actual_summary TEXT,               -- What actually happened
    divergences TEXT,                  -- JSON array of {type, description, severity}
    divergence_classification TEXT,    -- good (better approach) or bad (shortcut/mistake)

    -- Extracted learnings
    patterns_found TEXT,               -- JSON array of patterns
    gotchas_found TEXT,                -- JSON array of gotchas
    decisions_made TEXT,               -- JSON array of architecture decisions

    -- Actions taken
    improvements_made TEXT,            -- JSON array of {type, target, change}
    kb_entries_created TEXT,           -- JSON array of knowledge IDs created
    claude_md_updated INTEGER DEFAULT 0,
    templates_updated TEXT,            -- JSON array of template paths

    -- Review metadata
    reviewed_at TEXT DEFAULT (datetime('now')),
    review_duration_seconds INTEGER,
    auto_review INTEGER DEFAULT 1      -- 1 = automatic, 0 = human-triggered
);

CREATE INDEX IF NOT EXISTS idx_system_reviews_agent ON system_reviews(agent_type);
CREATE INDEX IF NOT EXISTS idx_system_reviews_outcome ON system_reviews(outcome);
CREATE INDEX IF NOT EXISTS idx_system_reviews_idea ON system_reviews(idea_slug);

-- ============================================================================
-- IMPROVEMENT METRICS TABLE
-- Track system improvement over time
-- ============================================================================

CREATE TABLE IF NOT EXISTS improvement_metrics (
    id TEXT PRIMARY KEY,
    metric_type TEXT NOT NULL,
    value REAL NOT NULL,

    -- Context
    agent_type TEXT,
    idea_slug TEXT,
    context TEXT,                      -- JSON with additional context

    -- Time
    period_start TEXT,                 -- For aggregated metrics
    period_end TEXT,
    recorded_at TEXT DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_improvement_metrics_type ON improvement_metrics(metric_type);
CREATE INDEX IF NOT EXISTS idx_improvement_metrics_time ON improvement_metrics(recorded_at);

-- ============================================================================
-- KNOWLEDGE BASE EXTENSIONS
-- Add columns to existing knowledge table
-- ============================================================================

-- Note: ALTER TABLE in SQLite is limited, so we add columns one at a time
-- These may fail if columns already exist, which is fine

-- File pattern for gotcha matching (e.g., "*.ts", "server/routes/*")
-- Run: ALTER TABLE knowledge ADD COLUMN file_pattern TEXT;

-- Action type for pattern matching (CREATE, UPDATE, etc.)
-- Run: ALTER TABLE knowledge ADD COLUMN action_type TEXT;

-- Which agent discovered this knowledge
-- Run: ALTER TABLE knowledge ADD COLUMN discovered_by TEXT;

-- Source session/execution
-- Run: ALTER TABLE knowledge ADD COLUMN source_session TEXT;

-- ============================================================================
-- GOTCHA INJECTION VIEW
-- Makes it easy to find relevant gotchas for a task
-- ============================================================================

CREATE VIEW IF NOT EXISTS v_gotchas_for_tasks AS
SELECT
    k.id,
    k.content as gotcha,
    k.topic,
    k.file_pattern,
    k.action_type,
    k.confidence,
    k.created_at
FROM knowledge k
WHERE k.item_type = 'gotcha'
  AND k.superseded_by IS NULL
ORDER BY k.confidence DESC, k.created_at DESC;

-- ============================================================================
-- PATTERNS VIEW
-- Makes it easy to find patterns for spec generation
-- ============================================================================

CREATE VIEW IF NOT EXISTS v_patterns AS
SELECT
    k.id,
    k.content as pattern,
    k.topic,
    k.action_type,
    k.evidence as usage_examples,
    k.confidence,
    k.created_at
FROM knowledge k
WHERE k.item_type = 'pattern'
  AND k.superseded_by IS NULL
ORDER BY k.confidence DESC, k.created_at DESC;

-- ============================================================================
-- BUILD PROGRESS VIEW
-- Easy view of build execution progress
-- ============================================================================

CREATE VIEW IF NOT EXISTS v_build_progress AS
SELECT
    be.id as execution_id,
    s.idea_slug,
    s.user_slug,
    be.loop_id,
    be.branch_name,
    be.status,
    be.tasks_completed,
    be.tasks_total,
    be.tasks_failed,
    CASE
        WHEN be.tasks_total > 0
        THEN ROUND(100.0 * be.tasks_completed / be.tasks_total, 1)
        ELSE 0
    END as progress_pct,
    be.started_at,
    be.completed_at,
    CASE
        WHEN be.completed_at IS NOT NULL AND be.started_at IS NOT NULL
        THEN ROUND((julianday(be.completed_at) - julianday(be.started_at)) * 24 * 60, 1)
        ELSE NULL
    END as duration_minutes
FROM build_executions be
JOIN specifications s ON be.spec_id = s.id;

-- ============================================================================
-- IMPROVEMENT TRENDS VIEW
-- Track improvement over time
-- ============================================================================

CREATE VIEW IF NOT EXISTS v_improvement_trends AS
SELECT
    metric_type,
    agent_type,
    DATE(recorded_at) as date,
    AVG(value) as avg_value,
    MIN(value) as min_value,
    MAX(value) as max_value,
    COUNT(*) as sample_count
FROM improvement_metrics
GROUP BY metric_type, agent_type, DATE(recorded_at)
ORDER BY date DESC;
