-- Migration 102: Add metadata column to task_appendices
-- Purpose: Store structured metadata including scope for acceptance criteria
-- Part of: Test Scope Categorization Feature
-- Backward compatible: metadata defaults to NULL for existing appendices
--
-- Metadata JSON structure:
-- {
--   "scope": "codebase" | "api" | "ui" | "database" | "integration",
--   "priority": "required" | "optional",
--   "autoGenerated": boolean
-- }

-- Add metadata column for JSON storage
ALTER TABLE task_appendices ADD COLUMN metadata TEXT;

-- Create index for scope lookups via JSON extract
CREATE INDEX IF NOT EXISTS idx_task_appendices_scope
  ON task_appendices(json_extract(metadata, '$.scope'));
