-- Migration 133: Task Questions
-- Purpose: Persist questions generated by QuestionEngine for task clarification

CREATE TABLE IF NOT EXISTS task_questions (
  id TEXT PRIMARY KEY,
  task_id TEXT NOT NULL,
  category TEXT NOT NULL,
  text TEXT NOT NULL,
  priority INTEGER NOT NULL DEFAULT 5,
  importance TEXT NOT NULL DEFAULT 'optional',
  target_field TEXT,
  answer TEXT,
  answered_at TEXT,
  skipped INTEGER NOT NULL DEFAULT 0,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_task_questions_task ON task_questions(task_id);
CREATE INDEX IF NOT EXISTS idx_task_questions_task_status ON task_questions(task_id, skipped);
